### ISSUE TITLE
Add an example HTTP request test

### ISSUE THREAD

**Issue by munkyjunky** [munkyjunky/generator-hubot-script-babel#5]
Add an example HTTP request test to the hubot script tests to give an example of how to test hubot webhooks.

**Comment by kendaleiv** [comment]
Is this what you're looking for? https://github.com/ritterim/hubot-azure-alert-notifier/blob/master/test/index.js

**Comment by munkyjunky** [comment]
Yes! It was actually going through your repository after you mentioned it in #2 that reminded me I was intending to add that in.
